# Generated by Django 4.1.3 on 2022-11-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userregistration_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=30)),
                ('Phone_No', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=20)),
                ('City', models.CharField(max_length=20)),
                ('Pincode', models.CharField(max_length=20)),
                ('Username', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
                ('Confirm_password', models.CharField(max_length=20)),
            ],
        ),
    ]
