# Generated by Django 4.1.3 on 2022-12-16 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0003_product_tb_description'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Count', models.CharField(max_length=20)),
                ('Price', models.CharField(max_length=20)),
                ('ProductId', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='site_admin.product_tb')),
                ('UserId', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='user.userregistration_tb')),
            ],
        ),
    ]
