# Generated by Django 4.1.3 on 2022-12-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_cart_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration_tb',
            name='Status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
