# Generated by Django 4.1.3 on 2022-12-30 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0006_delete_bakerproductadmin_tb'),
        ('user', '0004_cart_tb_bakerproductid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_tb',
            name='ProductId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='site_admin.product_tb'),
        ),
    ]
