# Generated by Django 4.1.3 on 2022-12-31 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_cart_tb_productid'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=30)),
                ('Phone_No', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=20)),
                ('City', models.CharField(max_length=20)),
                ('Pincode', models.CharField(max_length=20)),
                ('GrandTotal', models.CharField(max_length=20)),
                ('Date', models.DateField()),
                ('Status', models.CharField(default='pending', max_length=20)),
                ('UserId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.userregistration_tb')),
            ],
        ),
    ]
