# Generated by Django 4.1.3 on 2022-12-31 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homebaker', '0009_alter_productbaker_tb_adminprice'),
        ('site_admin', '0006_delete_bakerproductadmin_tb'),
        ('user', '0006_order_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderItem_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Oid', models.CharField(max_length=20)),
                ('Quantity', models.CharField(max_length=20)),
                ('BakerProductId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homebaker.productbaker_tb')),
                ('ProductId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='site_admin.product_tb')),
            ],
        ),
    ]
