# Generated by Django 4.1.3 on 2022-12-31 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_orderitem_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem_tb',
            name='Price',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
