# Generated by Django 4.1.5 on 2023-02-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_feedback_tb_bakerid_feedback_tb_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration_tb',
            name='Proof',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
