# Generated by Django 4.1.5 on 2023-02-16 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0009_product_tb_stock'),
        ('homebaker', '0009_alter_productbaker_tb_adminprice'),
        ('user', '0011_userregistration_tb_proof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback_tb',
            name='BakerId',
        ),
        migrations.AddField(
            model_name='feedback_tb',
            name='BakerProductId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homebaker.productbaker_tb'),
        ),
        migrations.AddField(
            model_name='feedback_tb',
            name='ProductId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='site_admin.product_tb'),
        ),
    ]
