# Generated by Django 4.1.3 on 2023-03-11 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_order_tb_bakerproductid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_tb',
            name='BakerProductId',
        ),
    ]
