# Generated by Django 4.1.3 on 2023-03-11 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_remove_order_tb_bakerproductid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem_tb',
            name='Oid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.order_tb'),
        ),
    ]
