# Generated by Django 4.1.3 on 2022-12-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebaker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebakerregistration_tb',
            name='Proof',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
