# Generated by Django 4.1.3 on 2022-12-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebaker', '0002_homebakerregistration_tb_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebakerregistration_tb',
            name='Status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
