# Generated by Django 4.1.3 on 2022-12-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebaker', '0003_homebakerregistration_tb_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='productBaker_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.FileField(upload_to='')),
                ('Name', models.CharField(max_length=20)),
                ('Price', models.CharField(max_length=20)),
                ('Type', models.CharField(max_length=20)),
                ('Description', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
