# Generated by Django 4.1.3 on 2022-12-27 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homebaker', '0004_productbaker_tb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbaker_tb',
            name='Type',
        ),
    ]
