# Generated by Django 4.1.3 on 2022-12-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebaker', '0006_productbaker_tb_adminprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbaker_tb',
            name='AdminPrice',
            field=models.CharField(default=models.CharField(max_length=20), max_length=20),
        ),
    ]
