# Generated by Django 4.1.3 on 2023-03-11 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homebaker', '0009_alter_productbaker_tb_adminprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbaker_tb',
            name='BakerProductId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homebaker.homebakerregistration_tb'),
        ),
    ]
