# Generated by Django 4.1.3 on 2022-12-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.FileField(upload_to='')),
                ('Name', models.CharField(max_length=20)),
                ('Price', models.CharField(max_length=20)),
                ('Type', models.CharField(max_length=20)),
                ('Flavour', models.CharField(max_length=20)),
            ],
        ),
    ]
