# Generated by Django 4.1.3 on 2022-12-10 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0002_product_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_tb',
            name='Description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
