# Generated by Django 4.1.3 on 2022-12-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0003_product_tb_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_tb',
            name='AdminPrice',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
