# Generated by Django 4.1.3 on 2022-12-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0004_product_tb_adminprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='bakerProductAdmin_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.FileField(upload_to='')),
                ('Name', models.CharField(max_length=20)),
                ('Price', models.CharField(max_length=20)),
                ('AdminPrice', models.CharField(default=0, max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='product_tb',
            name='AdminPrice',
        ),
    ]
