# Generated by Django 4.1.3 on 2022-12-28 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0005_bakerproductadmin_tb_remove_product_tb_adminprice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bakerProductAdmin_tb',
        ),
    ]
