# Generated by Django 4.1.3 on 2023-01-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0006_delete_bakerproductadmin_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='tracking_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Oid', models.CharField(max_length=20)),
                ('Date', models.DateField()),
                ('Status', models.CharField(max_length=20)),
            ],
        ),
    ]
