# Generated by Django 4.1.3 on 2023-01-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0007_tracking_tb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking_tb',
            name='Status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
