# Generated by Django 4.1.5 on 2023-02-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0008_alter_tracking_tb_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_tb',
            name='Stock',
            field=models.CharField(default='', max_length=20),
        ),
    ]
