# Generated by Django 4.1.3 on 2023-03-18 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0009_product_tb_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminpayment_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameonCard', models.CharField(max_length=20)),
                ('CreditCardNumber', models.CharField(max_length=20)),
                ('CVV', models.CharField(max_length=20)),
                ('ExpDate', models.CharField(max_length=20)),
                ('Amount', models.CharField(max_length=20)),
                ('Oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_admin.tracking_tb')),
            ],
        ),
    ]
