# Generated by Django 4.1.3 on 2023-03-25 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_orderitem_tb_oid'),
        ('homebaker', '0010_productbaker_tb_bakerproductid'),
        ('site_admin', '0013_remove_adminpayment_tb_oid'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpayment_tb',
            name='Oid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.order_tb'),
        ),
        migrations.AddField(
            model_name='adminpayment_tb',
            name='bakerId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homebaker.homebakerregistration_tb'),
        ),
    ]
