# Generated by Django 4.1.7 on 2023-04-17 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_orderitem_tb_oid'),
        ('site_admin', '0014_adminpayment_tb_oid_adminpayment_tb_bakerid'),
    ]

    operations = [
        migrations.CreateModel(
            name='refundpayment_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameonCard', models.CharField(max_length=20)),
                ('CreditCardNumber', models.CharField(max_length=20)),
                ('CVV', models.CharField(max_length=20)),
                ('ExpDate', models.CharField(max_length=20)),
                ('Amount', models.CharField(max_length=20)),
                ('Oid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.order_tb')),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.userregistration_tb')),
            ],
        ),
    ]
