# Generated by Django 4.1.5 on 2023-02-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffregister_tb',
            name='Status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
