# Generated by Django 4.1.5 on 2023-02-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staffregister_tb_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffregister_tb',
            name='Proof',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
